[package]
name = "mediasan-cli"
edition = "2021"
version = "0.1.0"

publish = false

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.0.32", features = ["derive"] }
mp4san = { path = "../mp4san" }
webpsan = { path = "../webpsan" }
env_logger = "0.11.3"
log = "0.4.17"
